### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ghost**
License: GNU General Public License v3

### CODE REVIEW

**Comment by 0xCiBeR** [comment]
I don't think this license is suitable for MTA:DaYz proyect.

**Comment by ghost** [comment]
Why not? What would be a good license for the project then?

**Comment by 0xCiBeR** [comment]
A good license would be one made by us.

**Comment by ghost** [comment]
Maybe there is no need to reinvent the wheel. There are plenty of licenses available out there. Have you seen a few o them?

**Comment by neves768** [comment]
+ Everyone is permitted to copy and distribute verbatim copies
+ of this license document, but changing it is not allowed.
we can`t change it?

**Comment by neves768** [comment]
I agree with our own license, 'cause things like this:
"Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish)"
We're allowing for devs to modify something and sell it.

**Comment by ghost** [comment]
My main concern and the reason for proposing this license is that the project is not really open source without an open source license.
Code freedom means that more people can contribute to the project, making it an overall better game mode.

**Comment by 0xCiBeR** [comment]
The proposed license is not suit for our gamemode. I would suggest writting a new one from scratch. Closing this and thanks for your concern

**Pull request closed without merging**
