### PR TITLE
Achievement System

### PR DESCRIPTION
**Pull request by neves768**
- Added achievement system

Needs more testing, design renewal (i don't know if current design looks beautiful) and need to fill table with achievements

Ps: you can access achievement list through Journal

### CODE REVIEW

**Comment by 1B0Y** [comment]
Requires testing before it can be pushed to the branch. Nice work however

**Comment by neves768** [comment]
Every bug was fixed
Except: can't save achievements when player exit * working on *

**Comment by 1B0Y** [comment]
store achievements unlocked to a string using toJSON(), and send it to the server and store it to their account via setAccountData. To load the achievements, reverse it by getAccountData -> send to client -> fromJSON the string back into a table.

**Comment by neves768** [comment]
Done
Tested and everything is working.
I'm using GM save system to save achievements too

**Pull request merged**
